# Generated by Django 5.1.3 on 2024-11-25 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management_system_app', '0002_rename_end_date_event_date_rename_name_event_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('Technology', 'Technology'), ('Education', 'Education'), ('Culture', 'Culture'), ('Sports', 'Sports'), ('Religious', 'Religious'), ('Other', 'Other')], default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
